language: python
dist: focal

matrix:
  include:
    # These are quick and often catch errors, so list them first
    - python: 3.7
      env: CHECK_FORMATTING=1
    - python: 3.7
      env: CHECK_TYPING=1
    - python: pypy3.6-7.2.0
      dist: bionic
      env: RUNTIME_ONLY=1
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: nightly

script:
  - ci/travis.sh
